# Default values for konga.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: pantsel/konga
  tag: latest
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 80


# Konga default configuration
config: 
  db_adapter: postgres
  db_uri: 
  db_host: konga-dashboard-db
  db_port: 5432
  db_user: konga
  db_password: konga
  db_database: konga_database
  db_pg_schema: public


# LDAP configuration for Konga
ldap: {}
# ldap:
#   auth_provider:
#   host:
#   bind_dn:
#   bind_pass:
#   user_search_base:
#   user_search_filter:
#   user_attrs:
#   group_search_base:
#   group_search_filter:
#   group_attrs:
#   group_reg:
#   attr_username:
#   attr_firstname:
#   attr_lastname:
#   attr_email:

# Ingress Configuration for Konga
ingress:
  enabled: false
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths: []

  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local


resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
